name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  node:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - run: pnpm run lint
      - run: pnpm test --if-present
      - run: pnpm run build --if-present
